default:
  tasks:
  - "build"
  - "devmode"
build:
  tasks:
  - "clean"
  - "copy:sourcesToCompile"
  - "compile"
  - "copy:libsToDest"
  - "copy:compiledToDest"
build-prod:
  tasks:
  - "build"
  - "systemjs"
compile:
  tasks:
  - "ts"
devmode:
  tasks:
  - "configureRewriteRules"
  - "configureProxies:server"
  - "connect:server"
  - "browserSync"
  - "watch"
after-resources-watch:
  tasks:
  - "newer:copy:sourcesToCompile"
  - "compile"
  - "newer:copy:compiledToDest"
